# Generated by Django 6.0.7 on 2026-08-03 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("release_year", models.IntegerField(verbose_name="Год выхода")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posters/",
                        verbose_name="Постер",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("poster", models.URLField(blank=True)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added"],
                "unique_together": {("user", "imdb_id")},
            },
        ),
    ]
