# Generated by Django 6.0.7 on 2026-08-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
